networks:
  default:
    external: true
    name: finance-service_default
services:
  student-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-service
    ports:
      - "8090:8080"
    environment:
      # - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/student
      # - SPRING_DATASOURCE_USERNAME=appuser
      # - SPRING_DATASOURCE_PASSWORD=apppass
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_APPLICATION_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_APPLICATION_PASSWORD}
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_APPLICATION_USER}
      - MARIADB_PASSWORD=${DB_APPLICATION_PASSWORD}
      # - MARIADB_ROOT_PASSWORD=rootpass
      # - MARIADB_DATABASE=student
      # - MARIADB_USER=appuser
      # - MARIADB_PASSWORD=apppass
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    restart: always